#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# CoSolvKit
#
# Class to analyze cosolvent MD
#

import os
import sys
import json
from glob import glob
import logging
import numpy as np
import pandas as pd
from typing import Union

from scipy.signal import correlate

from MDAnalysis import Universe
from MDAnalysis.analysis import rdf, align, rms
from MDAnalysis.analysis.rms import RMSF

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("notebook", font_scale=1.2, rc={"lines.linewidth": 3})

from .hotspots_detection import HotspotDetector
from .consensus_detection import CrossProbeConsensusDetector
from .hotspot_visualization import (
    generate_consensus_pockets_session,
    generate_pharmacophore_session,
)
from .density_analysis import GridAnalysis, generate_pymol_session, generate_vmd_session


class Report:
    """Report class. This is the main class that takes care of post MD simulation processing and analysis.
    """
    def __init__(self, statistics_file, traj_file, top_file, cosolvent_names, out_path):
        """_summary_

        :param statistics_file: log file generated by MD Simulation. In CosolvKit this is called statistics.csv
        :type statistics_file: str
        :param traj_file: Trajectory file generated by MD Simulation.
        :type traj_file: str
        :param top_file: Topology file generated by CosolvKit.
        :type top_file: str
        :param cosolvents_names: list of cosolvent names to analyze.
        :type cosolvents_names: list[str]
        :param out_path: path to where to save the results.
        :type out_path: str
        """

        # Setup logging
        self.logger = logging.getLogger(__name__)

        self.cosolvent_names = cosolvent_names
        if cosolvent_names is None or len(cosolvent_names) == 0:
            self.logger.info("No cosolvents specified for the density analysis. At least one cosolvent is required.")
            sys.exit(1)

        self.trajectory = traj_file
        self.topology = top_file
        self.universe = Universe(self.topology, self.trajectory)

        self.out_path = out_path
        os.makedirs(self.out_path, exist_ok=True)
        # this will be checked when creating the sessions
        self.avg_pdb_path = os.path.join(self.out_path, "averaged_trajectory.pdb")

        self._volume = None
        self._temperature = None
        self._potential_energy = None

        self.statistics = statistics_file
        if statistics_file is not None:
            self._potential_energy, self._temperature, self._volume = self._get_temp_vol_pot(self.statistics)

        return

    def _plot_rmsf(self, rmsf_df):
        """Plots the RMSF of the protein residues.

        :param rmsf_df: dataframe with the RMSF data per atom.
        :type rmsf_df: pd.DataFrame
        """
        # Group by residue and calculate the mean RMSF
        rmsf_df = rmsf_df.groupby('residue').mean().reset_index()

        fig, ax = plt.subplots()
        ax.plot(rmsf_df['residue'], rmsf_df['RMSF'])
        ax.set_xlabel('Residue');        ax.set_ylabel('RMSF (A)')
        ax.set_title('RMSF by residue')
        plt.tight_layout()
        plt.savefig(os.path.join(self.out_path, "rmsf_by_residue.png"))
        plt.close()
        return

    def _plot_rmsd(self, rmsd_df, avg_selection):
        """Plots the RMSD of the protein residues.

        :param rmsd_df: dataframe with the RMSD data per frame.
        :type rmsd_df: pd.DataFrame
        :param avg_selection: selection string to average the trajectory.
        :type avg_selection: str
        """
        fig, ax = plt.subplots()
        ax.plot(rmsd_df['Frame'], rmsd_df[avg_selection])
        ax.set_xlabel('Frame');        ax.set_ylabel('RMSD (A)')
        ax.set_title(f'RMSD to Avg Structure - {avg_selection}')
        plt.tight_layout()
        plt.savefig(os.path.join(self.out_path, "rmsd_by_frame.png"))
        plt.close()
        return


    def _rmsf_analysis(self, avg_selection, align_selection):
        """Computes the RMSF of the protein residues.
        The funciton also generates the average structure of the trajectory and colors the residues by RMSF.
        This conformtion will be used as a reference for the pymol session.
        As for the density analysis, this function also asumes that the trajectory is already aligned.
        :param avg_selection: selection string to average the trajectory.
        :type avg_selection: str
        :param align_selection: selection string to align the trajectory to the average.
        :type align_selection: str
        """
        self.logger.info("Computing RMSF...")
        average = align.AverageStructure(self.universe, None,
                                        select=avg_selection,
                                        ).run()

        u_avg = average.results.universe

        R = rms.RMSD(self.universe, u_avg,
                    select=align_selection,
                    groupselections=[avg_selection],
                    ).run()

        avg_selection = avg_selection + ' and not name H*' # remove hydrogens from the selection
        rmsd_df = pd.DataFrame(R.rmsd,
                  columns=['Frame', 'Time (ps)', align_selection, avg_selection])

        rmsd_df.to_csv(os.path.join(self.out_path, "rmsd_by_frame.csv"))
        self._plot_rmsd(rmsd_df, avg_selection)

        selection = self.universe.select_atoms(avg_selection)
        residues = selection.resids
        rmsf = RMSF(selection).run()

        rmsf_df = pd.DataFrame({'residue': residues, 'RMSF': rmsf.results.rmsf})
        rmsf_df.index.name = 'atom'

        self.universe.add_TopologyAttr('tempfactors') # add empty attribute for all atoms
        for residue, r_value in zip(selection.residues, rmsf.results.rmsf):
            residue.atoms.tempfactors = r_value

        selection.write(self.avg_pdb_path)
        rmsf_df.to_csv(os.path.join(self.out_path, "rmsf_by_atom.csv"))
        self._plot_rmsf(rmsf_df)

        return


    def generate_report(self,
                        equilibration:bool=True, 
                        rmsf:bool=True, 
                        rdf:bool=False,
                        avg_selection:str="protein",
                        align_selection:str="protein and name CA"
                        ):
        """Creates the main plots for RDFs, autocorrelations and equilibration.
        :param equilibration: if True, the equilibration analysis will be performed, defaults to True
        :type equilibration: bool, optional
        :param rmsf: if True, the RMSF analysis will be performed, defaults to True
        :type rmsf: bool, optional
        :param rdf: if True, the RDF analysis will be performed, defaults to True
        :type rdf: bool, optional
        :param avg_selection: selection string to average the trajectory, defaults to "protein". Change this if you have other molecules in the system or things like DNA/RNA.
        :type avg_selection: str, optional
        :param align_selection: selection string to align the trajectory to the average, defaults to "protein and name CA". Change this if you have other molecules in the system or things like DNA/RNA.
        :type align_selection: str, optional
        """
        self.logger.info("Generating report...")

        if equilibration:
            if self.statistics is None:
                self.logger.warning("No statistics file found. Skipping equilibration analysis.")
            else:
                self._equilibration_analysis()
        if rmsf:
            self._rmsf_analysis(avg_selection, align_selection)
        if rdf:
            self._rfd_analysis(self.universe, self.cosolvent_names)

        return

    def _load_atomtype_definitions(self, atomtypes_fname:str=None) -> list:
        """Loads atom type definitions from a json file.
        :param atomtypes_fname: Path to the json file with atom type definitions.
        :type atomtypes_fname: str
        :return: A list of atom types definitions based on SMARTS patterns.
        :rtype: list
        """
        default_at_location = os.path.join(os.path.dirname(__file__), 'data/default_atomtypes.json')
        if (atomtypes_fname is None) or (not os.path.exists(atomtypes_fname)):
            self.logger.warning("Warning: Atom types definitions file not found or not provided.\n Using default atom types definitions.")
            try:
                with open(default_at_location) as fi:
                    data = json.load(fi)
                    typer_name = next(iter(data))
                    atomtypes_definitions = data[typer_name]
                    self.logger.info(f"Loaded {typer_name} atom types definitions.")
            except FileNotFoundError:
                self.logger.error(f"Error: Default atom types definitions not found @ {default_at_location}")
                sys.exit(1)
        else:
            with open(atomtypes_fname) as fi:
                data = json.load(fi)
                typer_name = next(iter(data))
                atomtypes_definitions = data[typer_name]
                self.logger.info(f"Loaded {typer_name} atom types definitions.")

        return atomtypes_definitions

    def generate_density_maps(self,
                              cosolvent_names:list[str]=None,
                              use_atomtypes:bool=True,
                              atomtypes_definitions:str=None,
                              gridsize:float=0.5,
                              temperature:float=None,
                              ):
        """Generates the density maps for all the cosolvents especified. It is possible to use atomtypes for the analysis.
        If no atomtypes are specified, the default atomtypes are used: HBD, HBA, Car.
        :param cosolvent_names: list of cosolvent names to analyze, defaults to None.
        :type cosolvent_names: list[str], optional
        :param use_atomtypes: if True, the density analysis will be performed using atomtypes, defaults to True
        :type use_atomtypes: bool, optional
        :param atomtypes_definitions: path to the json file with the atom types definitions, defaults to None
        :type atomtypes_definitions: str, optional
        :param gridsize: gridsize to use for the analysis, defaults to 0.5
        :type gridsize: float, optional
        :param temperature: temperature to use for the analysis, defaults to None
        :type temperature: float, optional

        """
        self.logger.info("Generating density maps...")

        if cosolvent_names is None or len(cosolvent_names) == 0:
            self.logger.warning("No cosolvents specified for the density analysis. Using all cosolvents specified in the Report class...")
            cosolvent_names = self.cosolvent_names

        if temperature is None: # If temperature is not passed, so we take the last one from statistics
            if self._temperature is None:
                self.logger.error("No temperature found. Please provide a temperature or a statistics file for the density analysis.")
                sys.exit(1)
            else:
                self.logger.warning(f'No temperature provided. Using the last temperature from the statistics file: {self._temperature[-1]}')
                temperature = self._temperature[-1]

        # load the atomtypes definitions
        if use_atomtypes:
            atomtypes_definitions = self._load_atomtype_definitions(atomtypes_definitions)

        for cosolvent in cosolvent_names:
            agfe_file = os.path.join(self.out_path, f"map_agfe_{cosolvent}.dx")
            per_type_files = sorted(
                f for f in glob(os.path.join(self.out_path, f"map_agfe_*_{cosolvent}.dx"))
                if 'raw' not in os.path.basename(f)
            )
            if os.path.isfile(agfe_file) or per_type_files:
                self.logger.info(f"Density maps for {cosolvent} already exist, skipping analysis.")
                continue

            atomgroup = self.universe.select_atoms(f"resname {cosolvent}")
            if atomgroup.n_atoms == 0:
                self.logger.error("Error: the provided selection didn't match any atoms.")
                sys.exit(1)

            analysis = GridAnalysis(atomgroup,
                                gridsize=gridsize,
                                use_atomtypes=use_atomtypes,
                                atomtypes_definitions=atomtypes_definitions,
                                verbose=True)
            analysis.run()
            # analysis.export_density(os.path.join(self.out_path, f"map_rawdensity_{cosolvent}.dx"))
            analysis.atomic_grid_free_energy(temperature, smoothing=True)
            analysis.export_atomic_grid_free_energy(os.path.join(self.out_path, f"map_agfe_{cosolvent}.dx"))
            # analysis.export_raw_atomic_grid_free_energy(os.path.join(self.out_path, f"map_agfe_raw_{cosolvent}.dx"))

        return

    def _get_temp_vol_pot(self, statistics_file):
        """Returns temperature, volume and potential energy of the system during the MD simulation.

        :param statistics_file: log file generated by the MD simulation. In CosolvKit is statistics.csv.
        :type statistics_file: str
        :return: potential energy, temperature and volume of the system for each frame.
        :rtype: tuple(list, list, list)
        """
        df = pd.read_csv(statistics_file)
        pot_e = list(df["Potential Energy (kJ/mole)"])
        temp = list(df["Temperature (K)"])
        vol = list(df["Box Volume (nm^3)"])
        return pot_e, temp, vol

    def _equilibration_analysis(self):
        """Plot equilibration data: potential energy, temperature and volume.

        """
        self.logger.info('Plotting equilibration data..')

        fig, axs = plt.subplots(3, 1, figsize=(12, 6))

        axs[0].plot(self._potential_energy, color='green', linewidth=2)
        axs[0].set_title('Potential Energy',)
        axs[0].set_xlabel('Frames')
        axs[0].set_ylabel('Energy (kJ/mole)')

        axs[1].plot(self._volume, color='blue', linewidth=2)
        axs[1].set_title('Volume')
        axs[1].set_xlabel('Frames')
        axs[1].set_ylabel('Volume (nm³)')

        axs[2].plot(self._temperature, color='red', linewidth=2)
        axs[2].set_title('Temperature')
        axs[2].set_xlabel('Frames')
        axs[2].set_ylabel('Temperature (K)')

        plt.tight_layout()
        plt.savefig(os.path.join(self.out_path, "equilibration_statistics.png"))
        plt.close()

        return

    def _rfd_analysis(self, universe: Universe, cosolvent_names: list):
        """Generates the plots for RDFs and Autocorrelations.

        :param universe: MD Analysis Universe that is created from the topology and trajectories.
        :type universe: Universe
        :param cosolvent_names: list of cosolvent resnames in the system
        :type cosolvent_names: list
        """
        np.seterr(divide='ignore', invalid='ignore')

        outpath = os.path.join(self.out_path, "RDFs")
        os.makedirs(outpath, exist_ok=True)

        self.logger.info("Running RDF analysis...")

        wat_resname = "HOH"
        # if top.endswith("cosolv_system.prmtop"):
        #     wat_resname = "WAT"
        oxygen_atoms = universe.select_atoms(f"resname {wat_resname} and name O")
        sim_frames = len(universe.trajectory)
        step_size = int(sim_frames/250)
        if step_size < 1:
            step_size = 1
        n_bins = 150
        for cosolvent_name in cosolvent_names:
            r_max = 15

            cosolvent_residues = universe.select_atoms(f'resname {cosolvent_name}')
            atoms_names = cosolvent_residues.residues[0].atoms.names
            for cosolvent_atom in set(atoms_names):
                max_y = 0
                if "H" in cosolvent_atom: continue
                self.logger.info(f"Analysing {cosolvent_name}-{cosolvent_atom}")
                fig, ax = plt.subplots(2, 2, sharex=False, sharey=False)
                plt.tight_layout(pad=3.0)
                # Here compute RDF between same atoms and different molecules
                atoms = cosolvent_residues.select_atoms(f'name {cosolvent_atom}')
                irdf = rdf.InterRDF(atoms, atoms, nbins=n_bins, range=(0.0, r_max), exclusion_block=(1, 1))
                irdf.run(start=0, step=step_size)
                max_y = max(irdf.results.rdf)
                ax[0][0].plot(irdf.results.bins, irdf.results.rdf, label="RDF")
                ax[0][0].set_xlabel(r'$r$ $\AA$')
                ax[0][0].set_ylabel("$g(r)$")
                ax[0][0].set_title(f"RDF-{cosolvent_name} {cosolvent_atom}")
                # ax[0][0].set_title(f"RDF-{cosolvent_name} {cosolvent_atom} every {step_size} frames")
                leg = ax[0][0].legend(handlelength=0, handletextpad=0, fancybox=True)
                for item in leg.legend_handles:
                    item.set_visible(False)

                ax[1][0] = self._plot_autocorrelation(data=irdf.results.rdf,
                                                        ax=ax[1][0],
                                            cosolvent_name1=cosolvent_name,
                                            cosolvent_atom1=cosolvent_atom,
                                            cosolvent_name2=cosolvent_name,
                                            cosolvent_atom2=cosolvent_atom)
                # Here compute RDF between atom and water's oxygen
                irdf = rdf.InterRDF(atoms, oxygen_atoms, nbins=n_bins, range=(0.0, r_max))
                irdf.run(start=0, step=step_size)
                max_y = max(irdf.results.rdf)
                irdf.run()
                ax[0][1].plot(irdf.results.bins, irdf.results.rdf, label="RDF")
                ax[0][1].set_xlabel(r'$r$ $\AA$')
                ax[0][1].set_ylabel("$g(r)$")
                ax[0][1].set_title(f"RDF {cosolvent_name} {cosolvent_atom}-HOH O")
                # ax[0][1].set_title(f"RDF {cosolvent_name} {cosolvent_atom}-HOH O every {step_size} frames")
                leg = ax[0][1].legend(handlelength=0, handletextpad=0, fancybox=True)
                for item in leg.legend_handles:
                    item.set_visible(False)

                self._plot_autocorrelation(data=irdf.results.rdf,
                                             ax=ax[1][1],
                                             cosolvent_name1=cosolvent_name,
                                             cosolvent_atom1=cosolvent_atom,
                                             cosolvent_name2="HOH",
                                             cosolvent_atom2="O")
                if outpath is not None:
                    plt.savefig(f"{outpath}/rdf_{cosolvent_name}_{cosolvent_atom}.png")
                plt.close()

        # Finally do waters
        self.logger.info("Analysing water")
        r_max = 8.5
        fig, ax = plt.subplots()
        plt.setp(ax, xlim=(0, r_max+1))
        irdf = rdf.InterRDF(oxygen_atoms, oxygen_atoms, nbins=n_bins, range=(0.0, r_max), exclusion_block=(1, 1))
        irdf.run(start=0, step=50)
        # irdf.run()
        ax.plot(irdf.results.bins, irdf.results.rdf, label="RDF")
        ax.set_xlabel(r'$r$ $\AA$')
        ax.set_ylabel("$g(r)$")
        ax.set_title(f"RDF-HOH O every 50 frames")
        leg = ax.legend(handlelength=0, handletextpad=0, fancybox=True)
        for item in leg.legend_handles:
            item.set_visible(False)
        if outpath is not None:
            plt.savefig(f"{outpath}/rdf_HOH_O.png")
        plt.close()
        return

    def _autocorrelation(self, data):
        """Gets the autocorrelation values.

        :param data: list of data for which the autocorrelation has to be computed.
        :type data: list
        :return: list of autocorrelations.
        :rtype: list
        """
        n = len(data)
        mean = np.mean(data)
        autocorr = correlate(data - mean, data - mean, mode='full', method='auto')
        return autocorr[n - 1:]

    def _plot_autocorrelation(self, data, ax, cosolvent_name1=None, cosolvent_atom1=None, cosolvent_name2=None, cosolvent_atom2=None):
        """Plots autocorrelations.

        :param data: list of data points for which we want to plot autocorrelations.
        :type data: list
        :param ax: matplotlib axis to add the autocorrelation to the RDF plot.
        :type ax: matplotlib.pyplot.axisß
        :param cosolvent_name1: name of the first cosolvent molecule, defaults to None
        :type cosolvent_name1: str, optional
        :param cosolvent_atom1: name of the first atom, defaults to None
        :type cosolvent_atom1: str, optional
        :param cosolvent_name2: name of the second cosolvent molecule, defaults to None
        :type cosolvent_name2: str, optional
        :param cosolvent_atom2: name of the second atom, defaults to None
        :type cosolvent_atom2: str, optional
        :return: the axis with the autocorrelation plot
        :rtype: matplotlib.pyplot.axis
        """
        title = f"{cosolvent_name1} {cosolvent_atom1}-{cosolvent_name2} {cosolvent_atom2}"
        data = data[0::2]
        autocorr_values = self._autocorrelation(data)
        # Normalize autocorrelation values for better plotting
        normalized_autocorr = autocorr_values / np.max(np.abs(autocorr_values))
        lags = np.arange(0, len(autocorr_values))
        pd.plotting.autocorrelation_plot(pd.Series(normalized_autocorr), ax=ax, label="Autocorrelation")
        ax.grid(False)
        ax.set_xlim([0, len(autocorr_values)])
        ax.set_title(title)
        ax.set_xlabel('Lag')
        ax.set_ylabel('Autocorrelation')
        leg = ax.legend(handlelength=0, handletextpad=0, fancybox=True)
        for item in leg.legend_handles:
            item.set_visible(False)
        return ax

    def generate_hotspot_report(self,
                               cosolvent_names:list=None,
                               agfe_cutoff:float=-1.0,
                               min_cluster_voxels:int=20,
                               top_percentile:float=10.0,
                               score_weights:dict=None,
                               export_label_map:bool=True,
                               gridsize:float=0.5,
                               top_n_plot:int=10,
                               save_checkpoint:bool=True) -> dict:
        """Detect, score, and rank binding hotspots from AGFE density maps.

        Must be called after :meth:`generate_density_maps`.  Reads the ``.dx``
        files written to ``out_path``, clusters favorable voxels with
        connected-components analysis, and scores each site on:

        - **favorability** — mean AGFE of the most-favorable voxels (top percentile)
        - **diversity** — fraction of atom types (HBD/HBA/Car/Cal/Hal) favorable at the site
        - **volume** — normalised cluster size (proxy for pocket spatial extent)

        Note: persistence (fraction of trajectory occupied) is intentionally omitted
        because it is mathematically equivalent to AGFE via the Boltzmann relation
        AGFE = −kT·ln(P_local/P_bulk) and would double-count the favorability signal.

        :param cosolvent_names: cosolvents to analyse, defaults to all.
        :param agfe_cutoff: AGFE threshold in kcal/mol (default -1.0).
        :param min_cluster_voxels: minimum cluster size to retain (default 20).
        :param top_percentile: top-N% voxels used for favorability score (default 10.0).
        :param score_weights: dict with keys favorability/diversity/volume.
        :param export_label_map: write hotspot_labels_{cosolvent}.dx (default True).
        :param add_to_pymol: add hotspot spheres to existing .pse session (default True).
        :param gridsize: voxel size in Å, must match generate_density_maps (default 0.5).
        :param top_n_plot: maximum number of sites shown in the 3D plot, in rank order (default 10).
        :param save_checkpoint: if True (default), save a checkpoint under
            ``out_path/hotspot_checkpoints/`` so consensus can be re-run later
            without repeating this step.  Load via :meth:`load_hotspot_checkpoint`.
        :return: dict {cosolvent: List[BindingSite]} sorted by composite score.
        """
        if cosolvent_names is None:
            cosolvent_names = self.cosolvent_names

        detector = HotspotDetector(
            out_path=self.out_path,
            cosolvent_names=cosolvent_names,
            universe=self.universe,
            agfe_cutoff=agfe_cutoff,
            min_cluster_voxels=min_cluster_voxels,
            top_percentile=top_percentile,
            score_weights=score_weights,
            gridsize=gridsize,
        )
        results = detector.detect_all()
        detector.export_results(results, label_map=export_label_map)
        if save_checkpoint:
            HotspotDetector.save_checkpoint(results, self.out_path)

        for cosolvent, sites in results.items():
            if sites:
                detector.plot_hotspot_clustering_3d(
                    cosolvent,
                    sites=sites,
                    output_path=os.path.join(
                        self.out_path, f"clustering_3d_{cosolvent}.html"
                    ),
                    top_n=top_n_plot,
                )

        return results

    def load_hotspot_checkpoint(self, cosolvent_names: list = None) -> dict:
        """Load hotspot results from a previously saved checkpoint.

        Reads the NPZ files written by :meth:`generate_hotspot_report` (when
        ``save_checkpoint=True``) and reconstructs the full
        ``Dict[str, List[BindingSite]]`` structure — including voxel masks and
        grid metadata — needed by :meth:`generate_consensus_report`.

        Use this to re-run consensus detection with different parameters
        (``jaccard_threshold``, ``community_method``, ``score_weights``) without
        repeating the slow hotspot detection step.

        :param cosolvent_names: cosolvents to load, defaults to all cosolvents
            known to this :class:`Report`.
        :return: dict {cosolvent: List[BindingSite]}.
        :raises FileNotFoundError: if the checkpoint for any requested cosolvent
            is missing.
        """
        if cosolvent_names is None:
            cosolvent_names = self.cosolvent_names
        return HotspotDetector.load_checkpoint(self.out_path, cosolvent_names)

    def generate_consensus_report(self,
                                  probe_results: dict,
                                  jaccard_threshold: float = 0.05,
                                  community_method: str = "connected_components",
                                  score_weights: dict = None) -> list:
        """Group per-probe hotspots into cross-probe consensus binding sites.

        Must be called after :meth:`generate_hotspot_report` (pass its return
        value as ``probe_results``).  Sites from different cosolvents that share
        favorable voxels (Jaccard ≥ ``jaccard_threshold``) are grouped into
        communities.  Each community becomes a :class:`ConsensusSite` with a
        pharmacophore profile describing which atom types from which probes are
        favorable.

        Writes to ``out_path``:

        - ``consensus_sites.csv`` / ``consensus_sites.json`` — flat ranked table
        - ``consensus_sites_pharmacophore.json`` — nested per-probe/per-atom-type
          AGFE fingerprint

        :param probe_results: ``Dict[str, List[BindingSite]]`` from
            :meth:`generate_hotspot_report`.
        :param jaccard_threshold: minimum voxel-mask Jaccard similarity to link
            two sites (default 0.05).
        :param community_method: ``'connected_components'`` (default) or
            ``'greedy_modularity'`` (requires networkx ≥ 2.6).
        :param score_weights: dict with keys ``coverage``, ``favorability``,
            ``volume`` (normalised internally).
        :return: list of :class:`ConsensusSite` sorted by consensus_score.
        """
        detector = CrossProbeConsensusDetector(
            probe_results=probe_results,
            jaccard_threshold=jaccard_threshold,
            community_method=community_method,
            score_weights=score_weights,
        )
        consensus_sites = detector.detect_communities()
        detector.export_results(consensus_sites, out_path=self.out_path)

        reference_pdb = getattr(self, 'avg_pdb_path', None)
        generate_consensus_pockets_session(
            consensus_sites=consensus_sites,
            out_path=self.out_path,
            reference_pdb=reference_pdb,
        )
        generate_pharmacophore_session(
            consensus_sites=consensus_sites,
            out_path=self.out_path,
            reference_pdb=reference_pdb,
            top_n=3,
        )

        return consensus_sites

    def generate_pymol_session(self,
                               density_files: Union[str, list] = None,
                               selection_string: str = None,
                               reference_pdb: str = None):
        """Generate a PyMol session from the density maps. See
        :func:`cosolvkit.grid_analysis.generate_pymol_session` for full documentation.
        """
        generate_pymol_session(
            out_path=self.out_path,
            cosolvent_names=self.cosolvent_names,
            avg_pdb_path=self.avg_pdb_path,
            density_files=density_files,
            selection_string=selection_string,
            reference_pdb=reference_pdb,
            compute_avg_structure=lambda: self._rmsf_analysis(
                avg_selection='protein', align_selection='protein and name CA'
            ),
        )

    def generate_vmd_session(self, density_files: Union[str, list] = None):
        """Generate a VMD session script. See
        :func:`cosolvkit.grid_analysis.generate_vmd_session` for full documentation.
        """
        generate_vmd_session(
            out_path=self.out_path,
            topology=self.topology,
            trajectory=self.trajectory,
            density_files=density_files,
        )
