#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# CoSolvKit
#
# Class to analyze cosolvent MD
#

import os
import sys
import json
from glob import glob
import logging
import numpy as np
import pandas as pd
from typing import Union

from MDAnalysis import Universe

from cosolvkit.analysis.structural import qc
from cosolvkit.analysis.core.grid import GridAnalysis
from cosolvkit.analysis.sites.detect import HotspotDetector
from cosolvkit.analysis.sites.binding_sites import identify_binding_sites, export_binding_sites
from cosolvkit.analysis.viz.pymol import generate_pymol_session
from cosolvkit.analysis.viz.vmd import generate_vmd_session


class Report:
    """Post-MD processing and analysis of a single cosolvent simulation."""

    def __init__(self, traj_file, top_file, cosolvent_names, out_path):
        """
        :param traj_file: trajectory file generated by the MD simulation.
        :type traj_file: str
        :param top_file: topology file generated by CosolvKit.
        :type top_file: str
        :param cosolvent_names: cosolvent names to analyze.
        :type cosolvent_names: list[str]
        :param out_path: directory to save the results in.
        :type out_path: str
        """

        self.logger = logging.getLogger(__name__)

        self.cosolvent_names = cosolvent_names
        if cosolvent_names is None or len(cosolvent_names) == 0:
            self.logger.info("No cosolvents specified for the density analysis. At least one cosolvent is required.")
            sys.exit(1)

        self.trajectory = traj_file
        self.topology = top_file
        self.universe = Universe(self.topology, self.trajectory)

        self.out_path = out_path
        os.makedirs(self.out_path, exist_ok=True)
        # Written by the RMSF step; checked when creating the sessions.
        self.avg_pdb_path = os.path.join(self.out_path, "averaged_trajectory.pdb")

        self._volume = None
        self._temperature = None
        self._potential_energy = None

        return

    def _plot_rmsf(self, rmsf_df):
        """Delegate to qc._plot_rmsf."""
        qc._plot_rmsf(rmsf_df, self.out_path)

    def _plot_rmsd(self, rmsd_df, avg_selection):
        """Delegate to qc._plot_rmsd."""
        qc._plot_rmsd(rmsd_df, avg_selection, self.out_path)

    def _rmsf_analysis(self, avg_selection, align_selection):
        """Compute per-residue RMSF and write the average structure used as the session reference.

        Assumes the trajectory is already aligned.

        :param avg_selection: selection string to average the trajectory.
        :type avg_selection: str
        :param align_selection: selection string to align the trajectory to the average.
        :type align_selection: str
        """
        self.rmsf_df = qc.rmsf_analysis(self.universe, self.out_path, avg_selection, align_selection)
        return


    def generate_report(self,
                        rmsf:bool=True,
                        rdf:bool=False,
                        rmsf_avg_selec:str="protein",
                        align_selection:str="protein and name CA"
                        ):
        """Create the main structural QC plots (RMSF and RDFs/autocorrelations).

        :param rmsf: run the RMSF analysis.
        :type rmsf: bool, optional
        :param rdf: run the RDF analysis.
        :type rdf: bool, optional
        :param rmsf_avg_selec: selection string to average the trajectory.
        :type rmsf_avg_selec: str, optional
        :param align_selection: selection string to align the trajectory to the average.
        :type align_selection: str, optional
        """
        self.logger.info("Generating report...")

        if rmsf:
            self._rmsf_analysis(rmsf_avg_selec, align_selection)
        if rdf:
            self._rfd_analysis(self.universe, self.cosolvent_names)

        return

    def _load_atomtype_definitions(self, atomtypes_fname:str=None) -> list:
        """Load SMARTS-based atom type definitions, falling back to the packaged defaults.

        :param atomtypes_fname: path to a json file with atom type definitions.
        :type atomtypes_fname: str
        :return: atom type definitions.
        :rtype: list
        """
        default_at_location = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data/default_atomtypes.json')
        if (atomtypes_fname is None) or (not os.path.exists(atomtypes_fname)):
            self.logger.warning("Warning: Atom types definitions file not found or not provided.\n Using default atom types definitions.")
            try:
                with open(default_at_location) as fi:
                    data = json.load(fi)
                    typer_name = next(iter(data))
                    atomtypes_definitions = data[typer_name]
                    self.logger.info(f"Loaded {typer_name} atom types definitions.")
            except FileNotFoundError:
                self.logger.error(f"Error: Default atom types definitions not found @ {default_at_location}")
                sys.exit(1)
        else:
            with open(atomtypes_fname) as fi:
                data = json.load(fi)
                typer_name = next(iter(data))
                atomtypes_definitions = data[typer_name]
                self.logger.info(f"Loaded {typer_name} atom types definitions.")

        return atomtypes_definitions

    def _log_sampling_adequacy(self, analysis, cosolvent, gridsize, temperature,
                               atom_radius=1.4, n_kt=1.0):
        """Log whether a map is better sampled than its own Poisson noise.

        *n_kt* must match the cutoff the maps will later be thresholded at.
        """
        from cosolvkit.analysis.core.sampling import sampling_report
        try:
            rep = sampling_report(
                n_atoms=analysis._n_atoms,
                n_frames=analysis._nframes,
                n_accessible_voxels=analysis._n_accessible_voxels,
                sigma_voxels=(atom_radius / 3.0) / gridsize,
                n_kt=n_kt,
                temperature=temperature,
            )
        except (AttributeError, ValueError, ZeroDivisionError) as exc:
            self.logger.debug(f"Could not assess sampling for {cosolvent}: {exc}")
            return
        line = f"{cosolvent} {rep['summary']}"
        if rep["cutoff_below_noise_floor"]:
            self.logger.warning(line)
        else:
            self.logger.info(line)

    def generate_density_maps(self,
                              cosolvent_names:list[str]=None,
                              use_atomtypes:bool=True,
                              atomtypes_definitions:str=None,
                              gridsize:float=0.5,
                              temperature:float=None,
                              export_raw:bool=True,
                              n_kt:float=1.0,
                              ):
        """Write AGFE density maps ``map_agfe_[<atomtype>_]<cosolvent>.dx`` to ``out_path``.

        Existing maps are skipped rather than recomputed.

        :param cosolvent_names: cosolvents to analyze; defaults to all known to this Report.
        :type cosolvent_names: list[str], optional
        :param use_atomtypes: split the density per atom type.
        :type use_atomtypes: bool, optional
        :param atomtypes_definitions: path to a json file with atom type definitions;
            None uses the packaged defaults.
        :type atomtypes_definitions: str, optional
        :param gridsize: voxel size in Angstrom.
        :type gridsize: float, optional
        :param temperature: temperature in K; None takes the last value from the statistics file.
        :type temperature: float, optional
        :param export_raw: also write the unclamped ``map_agfe_raw_*.dx`` maps.
        :type export_raw: bool, optional
        :param n_kt: cutoff (in kT) the maps will be thresholded at; used only for the
            sampling-adequacy report.
        :type n_kt: float, optional
        """
        self.logger.info("Generating density maps...")

        if cosolvent_names is None or len(cosolvent_names) == 0:
            self.logger.warning("No cosolvents specified for the density analysis. Using all cosolvents specified in the Report class...")
            cosolvent_names = self.cosolvent_names

        if temperature is None:
            if self._temperature is None:
                self.logger.error("No temperature found. Please provide a temperature or a statistics file for the density analysis.")
                sys.exit(1)
            else:
                self.logger.warning(f'No temperature provided. Using the last temperature from the statistics file: {self._temperature[-1]}')
                temperature = self._temperature[-1]

        if use_atomtypes:
            atomtypes_definitions = self._load_atomtype_definitions(atomtypes_definitions)

        for cosolvent in cosolvent_names:
            agfe_file = os.path.join(self.out_path, f"map_agfe_{cosolvent}.dx")
            per_type_files = sorted(
                f for f in glob(os.path.join(self.out_path, f"map_agfe_*_{cosolvent}.dx"))
                if 'raw' not in os.path.basename(f)
            )
            if os.path.isfile(agfe_file) or per_type_files:
                self.logger.info(f"Density maps for {cosolvent} already exist, skipping analysis.")
                continue

            atomgroup = self.universe.select_atoms(f"resname {cosolvent}")
            if atomgroup.n_atoms == 0:
                self.logger.error("Error: the provided selection didn't match any atoms.")
                sys.exit(1)

            analysis = GridAnalysis(atomgroup,
                                gridsize=gridsize,
                                use_atomtypes=use_atomtypes,
                                atomtypes_definitions=atomtypes_definitions,
                                # so solvent_accessible_map_<RES>.dx lands beside the AGFE maps,
                                # where HotspotDetector looks for it. Without this it went to the
                                # cwd under one shared name and accessible_fraction was never
                                # populated despite carrying a non-zero default weight.
                                out_dir=self.out_path,
                                verbose=True)
            analysis.run()
            # analysis.export_density(os.path.join(self.out_path, f"map_rawdensity_{cosolvent}.dx"))
            analysis.atomic_grid_free_energy(temperature, smoothing=True)
            self._log_sampling_adequacy(analysis, cosolvent, gridsize, temperature,
                                        n_kt=n_kt)
            analysis.export_atomic_grid_free_energy(os.path.join(self.out_path, f"map_agfe_{cosolvent}.dx"))
            if export_raw:
                analysis.export_raw_atomic_grid_free_energy(os.path.join(self.out_path, f"map_agfe_raw_{cosolvent}.dx"))

        return

    def _rfd_analysis(self, universe, cosolvent_names):
        """Delegate to qc.rdf_analysis."""
        qc.rdf_analysis(universe, cosolvent_names, self.out_path)

    def _autocorrelation(self, data):
        """Delegate to qc.autocorrelation."""
        return qc.autocorrelation(data)

    def _plot_autocorrelation(self, data, ax, cosolvent_name1=None, cosolvent_atom1=None, cosolvent_name2=None, cosolvent_atom2=None):
        """Delegate to qc._plot_autocorrelation."""
        return qc._plot_autocorrelation(data, ax, cosolvent_name1, cosolvent_atom1, cosolvent_name2, cosolvent_atom2)

    def generate_hotspot_report(self,
                               cosolvent_names:list=None,
                               agfe_cutoff:float=-1.0,
                               min_cluster_volume_ang3:float=20.0,
                               top_percentile:float=10.0,
                               gridsize:float=0.5,
                               top_n_plot:int=10,
                               save_checkpoint:bool=True) -> dict:
        """Detect, score, and rank binding hotspots from the AGFE maps in ``out_path``.

        Must be called after :meth:`generate_density_maps`. Favorable voxels are
        clustered and each site scored on:

        - **favorability** — mean AGFE of the top-percentile voxels
        - **chemotype_diversity** — how many atom types are favorable at the site
          (requires atom-type-split maps). This describes the probe's chemistry at the
          site, not how many probes bound there — that is ``probe_coverage`` /
          ``probe_chemotype_coverage``.
        - **volume** — normalised cluster size

        Persistence is deliberately not a score component: it is the Boltzmann inverse
        of AGFE and would double-count favorability.

        :param cosolvent_names: cosolvents to analyse; defaults to all.
        :param agfe_cutoff: AGFE threshold in kcal/mol (negative = favorable).
        :param min_cluster_volume_ang3: minimum cluster size to retain, in A^3
            (grid-independent; one heavy atom at the 20.0 default).
        :param top_percentile: top-N% of voxels used for the favorability score.
        :param gridsize: voxel size in Angstrom; must match generate_density_maps.
        :param top_n_plot: number of sites shown in the 3D plot, in rank order.
        :param save_checkpoint: write a checkpoint under ``out_path/hotspot_checkpoints/``
            so binding-site detection can be re-run without repeating this step; load via
            :meth:`load_hotspot_checkpoint`.
        :return: dict {cosolvent: List[Hotspot]} sorted by composite score.
        """
        if cosolvent_names is None:
            cosolvent_names = self.cosolvent_names

        detector = HotspotDetector(
            out_path=self.out_path,
            cosolvent_names=cosolvent_names,
            universe=self.universe,
            agfe_cutoff=agfe_cutoff,
            min_cluster_volume_ang3=min_cluster_volume_ang3,
            top_percentile=top_percentile,
            gridsize=gridsize,
        )
        results = detector.detect_all()
        detector.export_results(results, label_map=True)
        if save_checkpoint:
            HotspotDetector.save_checkpoint(results, self.out_path)

        for cosolvent, sites in results.items():
            if sites:
                detector.plot_hotspot_clustering_3d(
                    cosolvent,
                    sites=sites,
                    output_path=os.path.join(
                        self.out_path, f"clustering_3d_{cosolvent}.html"
                    ),
                    top_n=top_n_plot,
                )

        return results

    def load_hotspot_checkpoint(self, cosolvent_names: list = None) -> dict:
        """Reload hotspots (with voxel masks and grid metadata) from a saved checkpoint.

        Lets binding-site detection be re-run with different parameters without
        repeating hotspot detection.

        :param cosolvent_names: cosolvents to load; defaults to all known to this Report.
        :return: dict {cosolvent: List[Hotspot]}.
        :raises FileNotFoundError: if a requested cosolvent has no checkpoint.
        """
        if cosolvent_names is None:
            cosolvent_names = self.cosolvent_names
        return HotspotDetector.load_checkpoint(self.out_path, cosolvent_names)

    def generate_binding_sites_report(self,
                                      probe_results: dict,
                                      connectivity: int = 26,
                                      weights: dict = None) -> list:
        """Group spatially overlapping hotspots into ranked cross-cosolvent binding sites.

        Must be called after :meth:`generate_hotspot_report`. Writes to ``out_path``:

        - ``binding_sites.csv`` / ``binding_sites.json`` — flat ranked table
        - ``binding_sites_pharmacophore.json`` — nested per-cosolvent/per-atom-type
          AGFE fingerprint

        :param probe_results: ``Dict[str, List[Hotspot]]`` from
            :meth:`generate_hotspot_report`.
        :param connectivity: voxel connectivity used to group hotspots (6, 18 or 26).
        :param weights: dict with keys ``coverage``, ``favorability``, ``volume``
            (normalised internally).
        :return: list of :class:`~cosolvkit.analysis.core.models.BindingSite`
            sorted by rank.
        """
        binding_sites = identify_binding_sites(
            probe_results, connectivity=connectivity, weights=weights,
        )
        export_binding_sites(binding_sites, self.out_path)

        return binding_sites

    def generate_pymol_session(self,
                               density_files: Union[str, list] = None,
                               selection_string: str = None,
                               reference_pdb: str = None):
        """Generate a PyMol session from the density maps.

        See :func:`cosolvkit.analysis.viz.pymol.generate_pymol_session` for the arguments.
        """
        generate_pymol_session(
            out_path=self.out_path,
            cosolvent_names=self.cosolvent_names,
            avg_pdb_path=self.avg_pdb_path,
            density_files=density_files,
            selection_string=selection_string,
            reference_pdb=reference_pdb,
            compute_avg_structure=lambda: self._rmsf_analysis(
                avg_selection='protein', align_selection='protein and name CA'
            ),
        )

    def generate_vmd_session(self, density_files: Union[str, list] = None):
        """Generate a VMD session script.

        See :func:`cosolvkit.analysis.viz.vmd.generate_vmd_session` for the arguments.
        """
        generate_vmd_session(
            out_path=self.out_path,
            topology=self.topology,
            trajectory=self.trajectory,
            density_files=density_files,
        )
