#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# CoSolvKit
#
# Class to analyze cosolvent MD
#

import os
import sys
import json
from glob import glob
import logging
import numpy as np
import pandas as pd
from typing import Union

from MDAnalysis import Universe

from cosolvkit.analysis.structural import qc
from cosolvkit.analysis.core.grid import GridAnalysis
from cosolvkit.analysis.sites.detect import HotspotDetector
from cosolvkit.analysis.sites.binding_sites import identify_binding_sites, export_binding_sites
from cosolvkit.analysis.viz.pymol import generate_pymol_session
from cosolvkit.analysis.viz.vmd import generate_vmd_session


class Report:
    """Report class. This is the main class that takes care of post MD simulation processing and analysis.
    """
    def __init__(self, traj_file, top_file, cosolvent_names, out_path):
        """_summary_

        :param traj_file: Trajectory file generated by MD Simulation.
        :type traj_file: str
        :param top_file: Topology file generated by CosolvKit.
        :type top_file: str
        :param cosolvents_names: list of cosolvent names to analyze.
        :type cosolvents_names: list[str]
        :param out_path: path to where to save the results.
        :type out_path: str
        """

        # Setup logging
        self.logger = logging.getLogger(__name__)

        self.cosolvent_names = cosolvent_names
        if cosolvent_names is None or len(cosolvent_names) == 0:
            self.logger.info("No cosolvents specified for the density analysis. At least one cosolvent is required.")
            sys.exit(1)

        self.trajectory = traj_file
        self.topology = top_file
        self.universe = Universe(self.topology, self.trajectory)

        self.out_path = out_path
        os.makedirs(self.out_path, exist_ok=True)
        # this will be checked when creating the sessions
        self.avg_pdb_path = os.path.join(self.out_path, "averaged_trajectory.pdb")

        self._volume = None
        self._temperature = None
        self._potential_energy = None

        return

    def _plot_rmsf(self, rmsf_df):
        """Delegate to qc._plot_rmsf."""
        qc._plot_rmsf(rmsf_df, self.out_path)

    def _plot_rmsd(self, rmsd_df, avg_selection):
        """Delegate to qc._plot_rmsd."""
        qc._plot_rmsd(rmsd_df, avg_selection, self.out_path)

    def _rmsf_analysis(self, avg_selection, align_selection):
        """Computes the RMSF of the protein residues.
        The funciton also generates the average structure of the trajectory and colors the residues by RMSF.
        This conformtion will be used as a reference for the pymol session.
        As for the density analysis, this function also asumes that the trajectory is already aligned.
        :param avg_selection: selection string to average the trajectory.
        :type avg_selection: str
        :param align_selection: selection string to align the trajectory to the average.
        :type align_selection: str
        """
        self.rmsf_df = qc.rmsf_analysis(self.universe, self.out_path, avg_selection, align_selection)
        return


    def generate_report(self,
                        rmsf:bool=True,
                        rdf:bool=False,
                        rmsf_avg_selec:str="protein",
                        align_selection:str="protein and name CA"
                        ):
        """Creates the main plots for RMSF and RDFs/autocorrelations.
        :param rmsf: if True, the RMSF analysis will be performed, defaults to True
        :type rmsf: bool, optional
        :param rdf: if True, the RDF analysis will be performed, defaults to True
        :type rdf: bool, optional
        :param rmsf_avg_selec: selection string to average the trajectory, defaults to "protein". Change this if you have other molecules in the system or things like DNA/RNA.
        :type rmsf_avg_selec: str, optional
        :param align_selection: selection string to align the trajectory to the average, defaults to "protein and name CA". Change this if you have other molecules in the system or things like DNA/RNA.
        :type align_selection: str, optional
        """
        self.logger.info("Generating report...")

        if rmsf:
            self._rmsf_analysis(rmsf_avg_selec, align_selection)
        if rdf:
            self._rfd_analysis(self.universe, self.cosolvent_names)

        return

    def _load_atomtype_definitions(self, atomtypes_fname:str=None) -> list:
        """Loads atom type definitions from a json file.
        :param atomtypes_fname: Path to the json file with atom type definitions.
        :type atomtypes_fname: str
        :return: A list of atom types definitions based on SMARTS patterns.
        :rtype: list
        """
        default_at_location = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data/default_atomtypes.json')
        if (atomtypes_fname is None) or (not os.path.exists(atomtypes_fname)):
            self.logger.warning("Warning: Atom types definitions file not found or not provided.\n Using default atom types definitions.")
            try:
                with open(default_at_location) as fi:
                    data = json.load(fi)
                    typer_name = next(iter(data))
                    atomtypes_definitions = data[typer_name]
                    self.logger.info(f"Loaded {typer_name} atom types definitions.")
            except FileNotFoundError:
                self.logger.error(f"Error: Default atom types definitions not found @ {default_at_location}")
                sys.exit(1)
        else:
            with open(atomtypes_fname) as fi:
                data = json.load(fi)
                typer_name = next(iter(data))
                atomtypes_definitions = data[typer_name]
                self.logger.info(f"Loaded {typer_name} atom types definitions.")

        return atomtypes_definitions

    def _log_sampling_adequacy(self, analysis, cosolvent, gridsize, temperature,
                               atom_radius=1.4, n_kt=1.0):
        """Log whether this map is better sampled than its own Poisson noise.

        *n_kt* must match the hotspot cutoff the maps will be thresholded at.
        """
        from cosolvkit.analysis.core.sampling import sampling_report
        try:
            rep = sampling_report(
                n_atoms=analysis._n_atoms,
                n_frames=analysis._nframes,
                n_accessible_voxels=analysis._n_accessible_voxels,
                sigma_voxels=(atom_radius / 3.0) / gridsize,
                n_kt=n_kt,
                temperature=temperature,
            )
        except (AttributeError, ValueError, ZeroDivisionError) as exc:
            self.logger.debug(f"Could not assess sampling for {cosolvent}: {exc}")
            return
        line = f"{cosolvent} {rep['summary']}"
        if rep["cutoff_below_noise_floor"]:
            self.logger.warning(line)
        else:
            self.logger.info(line)

    def generate_density_maps(self,
                              cosolvent_names:list[str]=None,
                              use_atomtypes:bool=True,
                              atomtypes_definitions:str=None,
                              gridsize:float=0.5,
                              temperature:float=None,
                              export_raw:bool=True,
                              n_kt:float=1.0,
                              ):
        """Generates the density maps for all the cosolvents especified. It is possible to use atomtypes for the analysis.
        If no atomtypes are specified, the default atomtypes are used: HBD, HBA, Car.
        :param cosolvent_names: list of cosolvent names to analyze, defaults to None.
        :type cosolvent_names: list[str], optional
        :param use_atomtypes: if True, the density analysis will be performed using atomtypes, defaults to True
        :type use_atomtypes: bool, optional
        :param atomtypes_definitions: path to the json file with the atom types definitions, defaults to None
        :type atomtypes_definitions: str, optional
        :param gridsize: gridsize to use for the analysis, defaults to 0.5
        :type gridsize: float, optional
        :param temperature: temperature to use for the analysis, defaults to None
        :type temperature: float, optional

        """
        self.logger.info("Generating density maps...")

        if cosolvent_names is None or len(cosolvent_names) == 0:
            self.logger.warning("No cosolvents specified for the density analysis. Using all cosolvents specified in the Report class...")
            cosolvent_names = self.cosolvent_names

        if temperature is None: # If temperature is not passed, so we take the last one from statistics
            if self._temperature is None:
                self.logger.error("No temperature found. Please provide a temperature or a statistics file for the density analysis.")
                sys.exit(1)
            else:
                self.logger.warning(f'No temperature provided. Using the last temperature from the statistics file: {self._temperature[-1]}')
                temperature = self._temperature[-1]

        # load the atomtypes definitions
        if use_atomtypes:
            atomtypes_definitions = self._load_atomtype_definitions(atomtypes_definitions)

        for cosolvent in cosolvent_names:
            agfe_file = os.path.join(self.out_path, f"map_agfe_{cosolvent}.dx")
            per_type_files = sorted(
                f for f in glob(os.path.join(self.out_path, f"map_agfe_*_{cosolvent}.dx"))
                if 'raw' not in os.path.basename(f)
            )
            if os.path.isfile(agfe_file) or per_type_files:
                self.logger.info(f"Density maps for {cosolvent} already exist, skipping analysis.")
                continue

            atomgroup = self.universe.select_atoms(f"resname {cosolvent}")
            if atomgroup.n_atoms == 0:
                self.logger.error("Error: the provided selection didn't match any atoms.")
                sys.exit(1)

            analysis = GridAnalysis(atomgroup,
                                gridsize=gridsize,
                                use_atomtypes=use_atomtypes,
                                atomtypes_definitions=atomtypes_definitions,
                                verbose=True)
            analysis.run()
            # analysis.export_density(os.path.join(self.out_path, f"map_rawdensity_{cosolvent}.dx"))
            analysis.atomic_grid_free_energy(temperature, smoothing=True)
            self._log_sampling_adequacy(analysis, cosolvent, gridsize, temperature,
                                        n_kt=n_kt)
            analysis.export_atomic_grid_free_energy(os.path.join(self.out_path, f"map_agfe_{cosolvent}.dx"))
            if export_raw:
                analysis.export_raw_atomic_grid_free_energy(os.path.join(self.out_path, f"map_agfe_raw_{cosolvent}.dx"))

        return

    def _rfd_analysis(self, universe, cosolvent_names):
        """Generates the plots for RDFs and Autocorrelations.
        Delegates to qc.rdf_analysis.
        """
        qc.rdf_analysis(universe, cosolvent_names, self.out_path)

    def _autocorrelation(self, data):
        """Gets the autocorrelation values. Delegates to qc.autocorrelation."""
        return qc.autocorrelation(data)

    def _plot_autocorrelation(self, data, ax, cosolvent_name1=None, cosolvent_atom1=None, cosolvent_name2=None, cosolvent_atom2=None):
        """Plots autocorrelations. Delegates to qc._plot_autocorrelation."""
        return qc._plot_autocorrelation(data, ax, cosolvent_name1, cosolvent_atom1, cosolvent_name2, cosolvent_atom2)

    def generate_hotspot_report(self,
                               cosolvent_names:list=None,
                               agfe_cutoff:float=-1.0,
                               min_cluster_voxels:int=20,
                               top_percentile:float=10.0,
                               gridsize:float=0.5,
                               top_n_plot:int=10,
                               save_checkpoint:bool=True) -> dict:
        """Detect, score, and rank binding hotspots from AGFE density maps.

        Must be called after :meth:`generate_density_maps`.  Reads the ``.dx``
        files written to ``out_path``, clusters favorable voxels with
        connected-components analysis, and scores each site on:

        - **favorability** — mean AGFE of the most-favorable voxels (top percentile)
        - **chemotype_diversity** — how many atom types (HBD/HBA/Car/Cal/Hal) are
          favorable at the site. Requires atom-type-split maps; this is a property of
          the probe's chemistry at the site, NOT of how many probes bound there (that
          is ``probe_coverage`` / ``probe_chemotype_coverage``).
        - **volume** — normalised cluster size (proxy for pocket spatial extent)

        Note: persistence (fraction of trajectory occupied) is intentionally omitted
        because it is mathematically equivalent to AGFE via the Boltzmann relation
        AGFE = −kT·ln(P_local/P_bulk) and would double-count the favorability signal.

        :param cosolvent_names: cosolvents to analyse, defaults to all.
        :param agfe_cutoff: AGFE threshold in kcal/mol (default -1.0).
        :param min_cluster_voxels: minimum cluster size to retain (default 20).
        :param top_percentile: top-N% voxels used for favorability score (default 10.0).
        :param gridsize: voxel size in Å, must match generate_density_maps (default 0.5).
        :param top_n_plot: maximum number of sites shown in the 3D plot, in rank order (default 10).
        :param save_checkpoint: if True (default), save a checkpoint under
            ``out_path/hotspot_checkpoints/`` so binding-site detection can be
            re-run later without repeating this step.  Load via
            :meth:`load_hotspot_checkpoint`.
        :return: dict {cosolvent: List[Hotspot]} sorted by composite score.
        """
        if cosolvent_names is None:
            cosolvent_names = self.cosolvent_names

        detector = HotspotDetector(
            out_path=self.out_path,
            cosolvent_names=cosolvent_names,
            universe=self.universe,
            agfe_cutoff=agfe_cutoff,
            min_cluster_voxels=min_cluster_voxels,
            top_percentile=top_percentile,
            gridsize=gridsize,
        )
        results = detector.detect_all()
        detector.export_results(results, label_map=True)
        if save_checkpoint:
            HotspotDetector.save_checkpoint(results, self.out_path)

        for cosolvent, sites in results.items():
            if sites:
                detector.plot_hotspot_clustering_3d(
                    cosolvent,
                    sites=sites,
                    output_path=os.path.join(
                        self.out_path, f"clustering_3d_{cosolvent}.html"
                    ),
                    top_n=top_n_plot,
                )

        return results

    def load_hotspot_checkpoint(self, cosolvent_names: list = None) -> dict:
        """Load hotspot results from a previously saved checkpoint.

        Reads the NPZ files written by :meth:`generate_hotspot_report` (when
        ``save_checkpoint=True``) and reconstructs the full
        ``Dict[str, List[Hotspot]]`` structure — including voxel masks and
        grid metadata — needed by :meth:`generate_binding_sites_report`.

        Use this to re-run binding-site detection with different parameters
        (``connectivity``, ``weights``) without repeating the slow hotspot
        detection step.

        :param cosolvent_names: cosolvents to load, defaults to all cosolvents
            known to this :class:`Report`.
        :return: dict {cosolvent: List[Hotspot]}.
        :raises FileNotFoundError: if the checkpoint for any requested cosolvent
            is missing.
        """
        if cosolvent_names is None:
            cosolvent_names = self.cosolvent_names
        return HotspotDetector.load_checkpoint(self.out_path, cosolvent_names)

    def generate_binding_sites_report(self,
                                      probe_results: dict,
                                      connectivity: int = 26,
                                      weights: dict = None) -> list:
        """Group per-cosolvent hotspots into ranked cross-cosolvent binding sites.

        Must be called after :meth:`generate_hotspot_report` (pass its return
        value as ``probe_results``).  Hotspots from different cosolvents that
        spatially overlap (voxel connectivity) are grouped into binding sites.
        Each site becomes a :class:`~cosolvkit.analysis.core.models.BindingSite`
        with a pharmacophore profile describing which atom types from which
        cosolvents are favorable.

        Writes to ``out_path``:

        - ``binding_sites.csv`` / ``binding_sites.json`` — flat ranked table
        - ``binding_sites_pharmacophore.json`` — nested per-cosolvent/per-atom-type
          AGFE fingerprint

        :param probe_results: ``Dict[str, List[Hotspot]]`` from
            :meth:`generate_hotspot_report`.
        :param connectivity: voxel connectivity used to group hotspots into a
            binding site (6, 18, or 26; default 26).
        :param weights: dict with keys ``coverage``, ``favorability``,
            ``volume`` (normalised internally).
        :return: list of :class:`~cosolvkit.analysis.core.models.BindingSite`
            sorted by rank.
        """
        binding_sites = identify_binding_sites(
            probe_results, connectivity=connectivity, weights=weights,
        )
        export_binding_sites(binding_sites, self.out_path)

        return binding_sites

    def generate_pymol_session(self,
                               density_files: Union[str, list] = None,
                               selection_string: str = None,
                               reference_pdb: str = None):
        """Generate a PyMol session from the density maps. See
        :func:`cosolvkit.grid_analysis.generate_pymol_session` for full documentation.
        """
        generate_pymol_session(
            out_path=self.out_path,
            cosolvent_names=self.cosolvent_names,
            avg_pdb_path=self.avg_pdb_path,
            density_files=density_files,
            selection_string=selection_string,
            reference_pdb=reference_pdb,
            compute_avg_structure=lambda: self._rmsf_analysis(
                avg_selection='protein', align_selection='protein and name CA'
            ),
        )

    def generate_vmd_session(self, density_files: Union[str, list] = None):
        """Generate a VMD session script. See
        :func:`cosolvkit.grid_analysis.generate_vmd_session` for full documentation.
        """
        generate_vmd_session(
            out_path=self.out_path,
            topology=self.topology,
            trajectory=self.trajectory,
            density_files=density_files,
        )
