#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# CoSolvKit
#
# Structural QC functions extracted from Report class.
# All computation and plotting logic is preserved verbatim;
# only the parameter source changes from self.X to explicit arguments.
#

import os
import logging
import numpy as np
import pandas as pd

from scipy.signal import correlate

from MDAnalysis import Universe
from MDAnalysis.analysis import rdf, align, rms
from MDAnalysis.analysis.rms import RMSF

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("notebook", font_scale=1.2, rc={"lines.linewidth": 3})

logger = logging.getLogger(__name__)


def _plot_rmsf(rmsf_df, out_path):
    """Plots the RMSF of the protein residues.

    :param rmsf_df: dataframe with the RMSF data per atom.
    :type rmsf_df: pd.DataFrame
    :param out_path: path to where to save the results.
    :type out_path: str
    """
    # Group by residue and calculate the mean RMSF
    rmsf_df = rmsf_df.groupby('residue').mean().reset_index()

    fig, ax = plt.subplots()
    ax.plot(rmsf_df['residue'], rmsf_df['RMSF'])
    ax.set_xlabel('Residue');        ax.set_ylabel('RMSF (A)')
    ax.set_title('RMSF by residue')
    plt.tight_layout()
    plt.savefig(os.path.join(out_path, "rmsf_by_residue.png"))
    plt.close()
    return


def _plot_rmsd(rmsd_df, avg_selection, out_path):
    """Plots the RMSD of the protein residues.

    :param rmsd_df: dataframe with the RMSD data per frame.
    :type rmsd_df: pd.DataFrame
    :param avg_selection: selection string to average the trajectory.
    :type avg_selection: str
    :param out_path: path to where to save the results.
    :type out_path: str
    """
    fig, ax = plt.subplots()
    ax.plot(rmsd_df['Frame'], rmsd_df[avg_selection])
    ax.set_xlabel('Frame');        ax.set_ylabel('RMSD (A)')
    ax.set_title(f'RMSD to Avg Structure - {avg_selection}')
    plt.tight_layout()
    plt.savefig(os.path.join(out_path, "rmsd_by_frame.png"))
    plt.close()
    return


def rmsf_analysis(universe, out_path, avg_selection, align_selection):
    """Computes the RMSF of the protein residues.
    The function also generates the average structure of the trajectory and colors the residues by RMSF.
    This conformation will be used as a reference for the pymol session.
    As for the density analysis, this function also assumes that the trajectory is already aligned.

    :param universe: MD Analysis Universe.
    :type universe: MDAnalysis.Universe
    :param out_path: path to where to save the results.
    :type out_path: str
    :param avg_selection: selection string to average the trajectory.
    :type avg_selection: str
    :param align_selection: selection string to align the trajectory to the average.
    :type align_selection: str
    :return: dataframe with the RMSF data per atom.
    :rtype: pd.DataFrame
    """
    logger.info("Computing RMSF...")
    average = align.AverageStructure(universe, None,
                                    select=avg_selection,
                                    ).run()

    u_avg = average.results.universe

    R = rms.RMSD(universe, u_avg,
                select=align_selection,
                groupselections=[avg_selection],
                ).run()

    avg_selection = avg_selection + ' and not name H*' # remove hydrogens from the selection
    rmsd_df = pd.DataFrame(R.rmsd,
              columns=['Frame', 'Time (ps)', align_selection, avg_selection])

    rmsd_df.to_csv(os.path.join(out_path, "rmsd_by_frame.csv"))
    _plot_rmsd(rmsd_df, avg_selection, out_path)

    selection = universe.select_atoms(avg_selection)
    residues = selection.resids
    rmsf = RMSF(selection).run()

    rmsf_df = pd.DataFrame({'residue': residues, 'RMSF': rmsf.results.rmsf})
    rmsf_df.index.name = 'atom'

    universe.add_TopologyAttr('tempfactors') # add empty attribute for all atoms
    for residue, r_value in zip(selection.residues, rmsf.results.rmsf):
        residue.atoms.tempfactors = r_value

    avg_pdb_path = os.path.join(out_path, "averaged_trajectory.pdb")
    selection.write(avg_pdb_path)
    rmsf_df.to_csv(os.path.join(out_path, "rmsf_by_atom.csv"))
    _plot_rmsf(rmsf_df, out_path)

    return rmsf_df


def equilibration_analysis(statistics_file, out_path):
    """Plot equilibration data: potential energy, temperature and volume.

    :param statistics_file: log file generated by the MD simulation. In CosolvKit is statistics.csv.
    :type statistics_file: str
    :param out_path: path to where to save the results.
    :type out_path: str
    """
    logger.info('Plotting equilibration data..')

    pot_e, temp, vol = _get_temp_vol_pot(statistics_file)

    fig, axs = plt.subplots(3, 1, figsize=(12, 6))

    axs[0].plot(pot_e, color='green', linewidth=2)
    axs[0].set_title('Potential Energy',)
    axs[0].set_xlabel('Frames')
    axs[0].set_ylabel('Energy (kJ/mole)')

    axs[1].plot(vol, color='blue', linewidth=2)
    axs[1].set_title('Volume')
    axs[1].set_xlabel('Frames')
    axs[1].set_ylabel('Volume (nm³)')

    axs[2].plot(temp, color='red', linewidth=2)
    axs[2].set_title('Temperature')
    axs[2].set_xlabel('Frames')
    axs[2].set_ylabel('Temperature (K)')

    plt.tight_layout()
    plt.savefig(os.path.join(out_path, "equilibration_statistics.png"))
    plt.close()

    return


def _get_temp_vol_pot(statistics_file):
    """Returns temperature, volume and potential energy of the system during the MD simulation.

    :param statistics_file: log file generated by the MD simulation. In CosolvKit is statistics.csv.
    :type statistics_file: str
    :return: potential energy, temperature and volume of the system for each frame.
    :rtype: tuple(list, list, list)
    """
    df = pd.read_csv(statistics_file)
    pot_e = list(df["Potential Energy (kJ/mole)"])
    temp = list(df["Temperature (K)"])
    vol = list(df["Box Volume (nm^3)"])
    return pot_e, temp, vol


def rdf_analysis(universe, cosolvent_names, out_path):
    """Generates the plots for RDFs and Autocorrelations.

    :param universe: MD Analysis Universe that is created from the topology and trajectories.
    :type universe: Universe
    :param cosolvent_names: list of cosolvent resnames in the system
    :type cosolvent_names: list
    :param out_path: path to where to save the results.
    :type out_path: str
    """
    np.seterr(divide='ignore', invalid='ignore')

    outpath = os.path.join(out_path, "RDFs")
    os.makedirs(outpath, exist_ok=True)

    logger.info("Running RDF analysis...")

    wat_resname = "HOH"
    # if top.endswith("cosolv_system.prmtop"):
    #     wat_resname = "WAT"
    oxygen_atoms = universe.select_atoms(f"resname {wat_resname} and name O")
    sim_frames = len(universe.trajectory)
    step_size = int(sim_frames/250)
    if step_size < 1:
        step_size = 1
    n_bins = 150
    for cosolvent_name in cosolvent_names:
        r_max = 15

        cosolvent_residues = universe.select_atoms(f'resname {cosolvent_name}')
        atoms_names = cosolvent_residues.residues[0].atoms.names
        for cosolvent_atom in set(atoms_names):
            max_y = 0
            if "H" in cosolvent_atom: continue
            logger.info(f"Analysing {cosolvent_name}-{cosolvent_atom}")
            fig, ax = plt.subplots(2, 2, sharex=False, sharey=False)
            plt.tight_layout(pad=3.0)
            # Here compute RDF between same atoms and different molecules
            atoms = cosolvent_residues.select_atoms(f'name {cosolvent_atom}')
            irdf = rdf.InterRDF(atoms, atoms, nbins=n_bins, range=(0.0, r_max), exclusion_block=(1, 1))
            irdf.run(start=0, step=step_size)
            max_y = max(irdf.results.rdf)
            ax[0][0].plot(irdf.results.bins, irdf.results.rdf, label="RDF")
            ax[0][0].set_xlabel(r'$r$ $\AA$')
            ax[0][0].set_ylabel("$g(r)$")
            ax[0][0].set_title(f"RDF-{cosolvent_name} {cosolvent_atom}")
            # ax[0][0].set_title(f"RDF-{cosolvent_name} {cosolvent_atom} every {step_size} frames")
            leg = ax[0][0].legend(handlelength=0, handletextpad=0, fancybox=True)
            for item in leg.legend_handles:
                item.set_visible(False)

            ax[1][0] = _plot_autocorrelation(data=irdf.results.rdf,
                                                    ax=ax[1][0],
                                        cosolvent_name1=cosolvent_name,
                                        cosolvent_atom1=cosolvent_atom,
                                        cosolvent_name2=cosolvent_name,
                                        cosolvent_atom2=cosolvent_atom)
            # Here compute RDF between atom and water's oxygen
            irdf = rdf.InterRDF(atoms, oxygen_atoms, nbins=n_bins, range=(0.0, r_max))
            irdf.run(start=0, step=step_size)
            max_y = max(irdf.results.rdf)
            irdf.run()
            ax[0][1].plot(irdf.results.bins, irdf.results.rdf, label="RDF")
            ax[0][1].set_xlabel(r'$r$ $\AA$')
            ax[0][1].set_ylabel("$g(r)$")
            ax[0][1].set_title(f"RDF {cosolvent_name} {cosolvent_atom}-HOH O")
            # ax[0][1].set_title(f"RDF {cosolvent_name} {cosolvent_atom}-HOH O every {step_size} frames")
            leg = ax[0][1].legend(handlelength=0, handletextpad=0, fancybox=True)
            for item in leg.legend_handles:
                item.set_visible(False)

            _plot_autocorrelation(data=irdf.results.rdf,
                                         ax=ax[1][1],
                                         cosolvent_name1=cosolvent_name,
                                         cosolvent_atom1=cosolvent_atom,
                                         cosolvent_name2="HOH",
                                         cosolvent_atom2="O")
            if outpath is not None:
                plt.savefig(f"{outpath}/rdf_{cosolvent_name}_{cosolvent_atom}.png")
            plt.close()

    # Finally do waters
    logger.info("Analysing water")
    r_max = 8.5
    fig, ax = plt.subplots()
    plt.setp(ax, xlim=(0, r_max+1))
    irdf = rdf.InterRDF(oxygen_atoms, oxygen_atoms, nbins=n_bins, range=(0.0, r_max), exclusion_block=(1, 1))
    irdf.run(start=0, step=50)
    # irdf.run()
    ax.plot(irdf.results.bins, irdf.results.rdf, label="RDF")
    ax.set_xlabel(r'$r$ $\AA$')
    ax.set_ylabel("$g(r)$")
    ax.set_title(f"RDF-HOH O every 50 frames")
    leg = ax.legend(handlelength=0, handletextpad=0, fancybox=True)
    for item in leg.legend_handles:
        item.set_visible(False)
    if outpath is not None:
        plt.savefig(f"{outpath}/rdf_HOH_O.png")
    plt.close()
    return


def autocorrelation(data):
    """Gets the autocorrelation values.

    :param data: list of data for which the autocorrelation has to be computed.
    :type data: list
    :return: list of autocorrelations.
    :rtype: np.ndarray
    """
    n = len(data)
    mean = np.mean(data)
    autocorr = correlate(data - mean, data - mean, mode='full', method='auto')
    return autocorr[n - 1:]


def _plot_autocorrelation(data, ax, cosolvent_name1=None, cosolvent_atom1=None, cosolvent_name2=None, cosolvent_atom2=None):
    """Plots autocorrelations.

    :param data: list of data points for which we want to plot autocorrelations.
    :type data: list
    :param ax: matplotlib axis to add the autocorrelation to the RDF plot.
    :type ax: matplotlib.pyplot.axis
    :param cosolvent_name1: name of the first cosolvent molecule, defaults to None
    :type cosolvent_name1: str, optional
    :param cosolvent_atom1: name of the first atom, defaults to None
    :type cosolvent_atom1: str, optional
    :param cosolvent_name2: name of the second cosolvent molecule, defaults to None
    :type cosolvent_name2: str, optional
    :param cosolvent_atom2: name of the second atom, defaults to None
    :type cosolvent_atom2: str, optional
    :return: the axis with the autocorrelation plot
    :rtype: matplotlib.pyplot.axis
    """
    title = f"{cosolvent_name1} {cosolvent_atom1}-{cosolvent_name2} {cosolvent_atom2}"
    data = data[0::2]
    autocorr_values = autocorrelation(data)
    # Normalize autocorrelation values for better plotting
    normalized_autocorr = autocorr_values / np.max(np.abs(autocorr_values))
    lags = np.arange(0, len(autocorr_values))
    pd.plotting.autocorrelation_plot(pd.Series(normalized_autocorr), ax=ax, label="Autocorrelation")
    ax.grid(False)
    ax.set_xlim([0, len(autocorr_values)])
    ax.set_title(title)
    ax.set_xlabel('Lag')
    ax.set_ylabel('Autocorrelation')
    leg = ax.legend(handlelength=0, handletextpad=0, fancybox=True)
    for item in leg.legend_handles:
        item.set_visible(False)
    return ax
